# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  2D_engine_config = debug

else ifeq ($(config),release)
  2D_engine_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := 2D-engine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

2D-engine:
ifneq (,$(2D_engine_config))
	@echo "==== Building 2D-engine ($(2D_engine_config)) ===="
	@${MAKE} --no-print-directory -C . -f 2D-engine.make config=$(2D_engine_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f 2D-engine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   2D-engine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"