set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Folder layout expected:
#   ${DOENGINE_SDL_EXTERNAL_DIR}/SDL/         (has its own CMakeLists.txt)
#   ${DOENGINE_SDL_EXTERNAL_DIR}/SDL_image/
#   ${DOENGINE_SDL_EXTERNAL_DIR}/SDL_ttf/
#   ${DOENGINE_SDL_EXTERNAL_DIR}/SDL_mixer/
#   ${DOENGINE_SDL_EXTERNAL_DIR}/SDL_net/
set(DOENGINE_SDL_EXTERNAL_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/doengine-shared/SDL2" CACHE PATH
    "Folder containing local SDL2 + family source trees")

option(DOENGINE_WITH_IMAGE "Bundle SDL2_image" ON)
option(DOENGINE_WITH_TTF   "Bundle SDL2_ttf"   ON)
option(DOENGINE_WITH_MIXER "Bundle SDL2_mixer" ON)
option(DOENGINE_WITH_NET   "Bundle SDL2_net"   ON)

option(DOENGINE_INSTALL_SYSTEM_SDL "Install SDL2 family into the system when built from source" ON)

include(GNUInstallDirs)
add_compile_definitions(FETCHED_CONTENT)
# Family is always built/used static -- it gets embedded into DOEngine.
set(SDL_SHARED OFF CACHE BOOL "" FORCE)
set(SDL_STATIC ON  CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(SDL2_DISABLE_INSTALL ${DOENGINE_INSTALL_SYSTEM_SDL} CACHE BOOL "" FORCE)
if(DOENGINE_INSTALL_SYSTEM_SDL)
    set(SDL2_DISABLE_INSTALL OFF CACHE BOOL "" FORCE)
endif()
set(SDL2IMAGE_INSTALL ${DOENGINE_INSTALL_SYSTEM_SDL} CACHE BOOL "" FORCE)
set(SDL2TTF_INSTALL   ${DOENGINE_INSTALL_SYSTEM_SDL} CACHE BOOL "" FORCE)
set(SDL2MIXER_INSTALL ${DOENGINE_INSTALL_SYSTEM_SDL} CACHE BOOL "" FORCE)
set(SDL2NET_INSTALL   ${DOENGINE_INSTALL_SYSTEM_SDL} CACHE BOOL "" FORCE)