macro(doengine_add_family NAME OPT SUBDIR)
    if(${OPT})
        find_package(${NAME} QUIET CONFIG)
        if(NOT ${NAME}_FOUND)
            message(STATUS "DOEngine: building ${NAME} from ${DOENGINE_SDL_EXTERNAL_DIR}/${SUBDIR}")
            add_subdirectory(${DOENGINE_SDL_EXTERNAL_DIR}/${SUBDIR} ${CMAKE_BINARY_DIR}/_${SUBDIR}_build)
        else()
            message(STATUS "DOEngine: using system ${NAME}")
        endif()
        doengine_resolve_target(_resolved
            ${NAME}::${NAME}-static ${NAME}-static ${NAME}::${NAME} ${NAME})
        list(APPEND _family ${_resolved})
    endif()
endmacro()